name: Build License Generator (EXE)

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: LicenseTool
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nuitka zstandard
      - name: Build EXE (no console)
        run: |
          python -m nuitka License_Generator.pyw `
            --onefile `
            --standalone `
            --assume-yes-for-downloads `
            --enable-plugin=pyside6 `
            --windows-disable-console `
            --output-filename=VisitorSuite_LicenseGenerator.exe
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: VisitorSuite_LicenseGenerator
          path: LicenseTool/VisitorSuite_LicenseGenerator.exe
